- name: PING
  hosts: Web
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
      
    - name: Start service httpd, if not started
      ansible.builtin.service:
      name: httpd
      state: started
