- name: install and run ngnix
  hosts: Web
  become: yes # -b become root access, like sudo
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and Enable Nginx Service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes