- name: Install and Run Nginx
  hosts: Web
  become: yes # Root access (like sudo)
  tasks:
    - name: Stop Apache if running (to prevent conflicts)
      ansible.builtin.service:
        name: httpd
        state: stopped
      ignore_errors: yes

    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and Enable Nginx Service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
