- name: variables
  hosts: local
  connection: local
  vars:
    COURSES: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar

  - name: Print the variables
    vars: # task level variables
      COURSES: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSES }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
    
  - name: Print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSES }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"