- name: variables
  hosts: local
  connections: local
  vars:
    COURSES: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: Print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSES }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"