- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: Print the variables
    vars: # task level variables can overwrite at variables
      COURSES: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSES }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
    
  - name: Print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSES }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"