---
- name: Loops Example 1
  hosts: local
  connection: local
  tasks:
    - name: Print names (Set 1)
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop:
        - Ramesh
        - Suresh
        - Hareesh

- name: Loops Example 2
  hosts: local
  connection: local
  tasks:
    - name: Print names (Set 2)
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop:
        - shashi
        - bhavani
        - mounika
        
