- name: Install Packages
  hosts: web_servers
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - gcc
        - git
        - zip
        - mysql
