- name: Install Packages
  hosts: web_servers
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: Installed
      loop:
      - nginx
      - gcc
      - git
      - zip
      - mysql